### PR TITLE
Dockerfile change to fix Docker build from GitHub repo

### PR DESCRIPTION
**Pull request by hmmccabe**

### CODE REVIEW

**Review by nealvis — APPROVED** [review]
looks good to me!

**Comment by jjo-in-pdx** [comment]
I haven't been able to build the docker image due to network issues so cannot test the change.  I tested this today on my development machine, last week I was unable to build the docker image on a fresh Ubuntu 16.04 install.  I followed Heather's instructions in https://jira01.devtools.intel.com/secure/attachment/787994/dockerproxyinstructions.txt
Details of my testing attached in file dockerfile_errors.txt

[dockerfile_errors.txt](https://github.com/movidius/ncsdk/files/1989582/dockerfile_errors.txt)

**Comment by nealvis** [comment]
@jjo-in-pdx can you test this on a network outside of the proxy/firewall?

**Review by jjo-in-pdx — APPROVED** [review]
After connecting to Intel guest wireless building docker image, running the docker image and make examples under docker all worked.

**Pull request merged**
