### PR TITLE
fix make api error

### PR DESCRIPTION
**Pull request by kapoopai**

### CODE REVIEW

**Comment by marktheunissen** [comment]
Yes same as https://github.com/movidius/ncsdk/pull/25 and https://github.com/movidius/ncsdk/pull/10,

None of which the developers of NCSDK seem interested in fixing. C'mon Intel, sort out your support, this is really bad!

**Comment by marktheunissen** [comment]
@nealvis, @ecopty, @ramanarachakonda ... more people trying to fix this simple issue, please merge this PR!

**Comment by marktheunissen** [comment]
@nealvis please merge these PRs -- I can see that you're actively maintaining this repo at Intel so why not fix these basic issues that have been around for 6+ months?

**Review by nealvis — APPROVED** [review]
as this PR is it will only work if running with sudo, going to merge it since it is broken all together as it is and then will add sudo as separate commit

**Pull request merged**
